"""
SCIPRA Canonical Results Generator.

This script computes and prints the authoritative table values for the
SCIPRA manuscript. These outputs are the source of truth — the manuscript
tables (Table 5, Table 7) should report the numbers produced here.

Usage:
    python generate_tables.py

All formulas strictly implement SI Appendix A. No hardcoded overrides.
"""

from pci_computation import DomainScores, pci, pci_nonlinear, rpci, rpci_raw, weighted_sigma

# ─── INPUT DATA ───────────────────────────────────────────────────────────────
# Domain scores from manuscript Table 5 (I, R, S calibrated per SI Appendix C).
# These are the FIXED inputs from the case study — do not modify.
SCENARIOS = {
    "A: Pre-Intervention (2010-2012)":  DomainScores(0.82, 0.48, 0.12),
    "B: Post-Charter III (2018-2021)":  DomainScores(0.70, 0.75, 0.55),
    "C: SCIPRA-Optimised (projected)":  DomainScores(0.75, 0.80, 0.79),
}
WEIGHTS = (0.30, 0.35, 0.35)  # w1=Investment, w2=Regulatory, w3=Stakeholder
LAMBDA  = 0.10                 # Dispersion-sensitivity parameter (SI Eq. 5)
BETA    = 0.50                 # Harmonic-Linear blend weight (SI Sec. 4.5)


# ─── TABLE 5: DOMAIN SCORES AND PCI ───────────────────────────────────────────
def table_5():
    print("\n" + "=" * 80)
    print("TABLE 5: Domain Scores, Linear PCI, and Non-Linear PCI")
    print("=" * 80)
    header = f"{'Scenario':<38} {'I':>6} {'R':>6} {'S':>6} {'PCI':>8} {'PCI-NL':>10}"
    print(header)
    print("-" * 80)
    for name, sc in SCENARIOS.items():
        print(
            f"{name:<38}"
            f" {sc.investment:>6.3f}"
            f" {sc.regulatory:>6.3f}"
            f" {sc.stakeholder:>6.3f}"
            f" {pci(sc, WEIGHTS):>8.3f}"
            f" {pci_nonlinear(sc, WEIGHTS, BETA):>10.3f}"
        )
    print()
    print("Notes:")
    print("  I = Investment domain score,  R = Regulatory domain score,  S = Stakeholder domain score")
    print("  Weights: w1=0.30, w2=0.35, w3=0.35  (Marikana legitimacy-emphasis calibration)")
    print("  PCI-NL: Harmonic-Linear blend (beta=0.50), WEIGHTED harmonic mean")


# ─── TABLE 7: RPCI AND DISPERSION ─────────────────────────────────────────────
def table_7():
    print("\n" + "=" * 80)
    print("TABLE 7: Robustness-Adjusted PCI (RPCI) — Normalized Form (SI Eq. A.10)")
    print("=" * 80)
    header = (
        f"{'Scenario':<38} {'PCI':>8} {'sigma':>8}"
        f" {'RPCI_raw':>10} {'RPCI_norm':>12}"
    )
    print(header)
    print("-" * 80)
    for name, sc in SCENARIOS.items():
        p0    = pci(sc, WEIGHTS)
        sig   = weighted_sigma(sc, WEIGHTS)
        r_raw = rpci_raw(sc, WEIGHTS, LAMBDA)
        r_nrm = rpci(sc, WEIGHTS, LAMBDA)
        print(
            f"{name:<38}"
            f" {p0:>8.3f}"
            f" {sig:>8.4f}"
            f" {r_raw:>10.3f}"
            f" {r_nrm:>12.3f}"
        )
    print()
    print("Notes:")
    print("  sigma = weighted standard deviation of domain scores (SI Eq. 6)")
    print("  RPCI_raw  = max(0, PCI - lambda*sigma)   [SI Eq. 5; used in Sec. 3.3 Remark]")
    print("  RPCI_norm = RPCI_raw / (1 + lambda/2)    [SI Eq. A.10; authoritative form]")
    print(f"  lambda = {LAMBDA} (dispersion-sensitivity parameter; Marikana calibration)")
    print()
    print("  IMPORTANT: The manuscript Remark in Section 3.3 cites values 0.427, 0.638, 0.752.")
    print("  These are RPCI_raw values for expositional simplicity (D=1.05 makes the")
    print("  difference ~4.8%). The authoritative RPCI for all proofs and tables is RPCI_norm.")


# ─── PARAMETER SUMMARY ────────────────────────────────────────────────────────
def parameter_summary():
    print("\n" + "=" * 80)
    print("PARAMETER SUMMARY (Full Reproducibility Checklist — SI Appendix B.7)")
    print("=" * 80)
    params = [
        ("PCI domain weights (w1, w2, w3)",   "0.30, 0.35, 0.35"),
        ("SIC coefficients (alpha, beta, gamma)", "0.30, 0.40, 0.30"),
        ("Dispersion sensitivity (lambda)",    "0.10"),
        ("Harmonic-Linear blend (beta)",       "0.50"),
        ("VADER urgency ceiling",              "0.10"),
        ("SVM random_state",                   "42"),
        ("CV n_splits",                        "5 (StratifiedKFold)"),
        ("TF-IDF max_features",                "500"),
        ("TF-IDF min_df / max_df",             "2 / 0.90"),
        ("Corpus size (N)",                    "87 documents"),
    ]
    for label, value in params:
        print(f"  {label:<45} {value}")


# ─── MAIN ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("\nSCIPRA CANONICAL RESULTS — Generated by generate_tables.py")
    print("These numbers are the authoritative source for manuscript Tables 5 & 7.")
    table_5()
    table_7()
    parameter_summary()
